### ISSUE TITLE
Dock Tab Behaviors

### ISSUE THREAD

**Issue by kerriganb** [npolyak/NP.Avalonia.UniDock#10]
Hey Nick, ... wondering if you have thoughts on how I can get access to tab selection event. 

What I need is the following:

- when docking framework (rehydrates) to know which tab items are (active/inactive - if any) - I suspect I can query XML directly for this (but a way to walk the DockManager tree would be great as well - or any other way you can think of ...)
- callback when user clicked on Tab (to activate) and which tab is going inactive

The reason for above is because we have very heavy processing, and we want to (disable) processing if tab is not visible (in active)

Now given your nice attached behaviors you have - i believe I can get this callback and attach events on the element - the problem is that the DockItemHeaderControl (is that the element I need to attach to)?? is in styles.xaml - and I hate to copy over that style - in order to add my attachedproperty to it (i.e. if you make an update - it might break my updated style)

anyway, hope what I asked makes sense - maybe you have some additional magic?

thanks
Kerrigan.

**Comment by npolyak** [comment]
I'll try to do it this Sunday. Should not be very difficult. 
Do I understand correctly that your heavy processing problem is non-visual, so that you simply want to stop it when a tab's content is hidden?

Thanks,

Nick

**Comment by kerriganb** [comment]
Hi Nick, your last update fixed the issue with non-active tabs unloading content -  I'm using a webcontrol in each tab, this works great (as control is no longer reloaded on tab activation). 

However because (webcontrols are heavy) - and we push a lot of visual updates (tabs typically contain web grids) - we would like to know when a tab has gone inactive - so we can tell the server - stop pushing updates to the (now invisible background tab webview)

so yah some sort of behavior we can hook into that says - this xyz tab has gone inactive - and this abc tab is about to activate would be awesome. This way we can tell server to stop pushing on inactive and start pushing on now active.

No rush (I was looking for pointers on how it could be done) - but (I think???) this might be useful for other folk using your framework as well to hook into these properties...

thank you!

Kerrigan.

**Comment by npolyak** [comment]
Not a problem - I am already working on it. Perhaps I'll release it tonight. If not - probably on Sunday.

**Comment by kerriganb** [comment]
You’re an awesome madman !

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by npolyak** [comment]
Hey Kerrigan, 

I think I added the features you've requested - as long as you use the DockItemViewModel(Base) you should be ok. 

I changed DockItemViewModelBase.IsSelected property to be true if and only if an item is a Tab item and it is selected within its tab group. If it is not a tab item or it is a tab item, but not selected within its tab group - it is false.

I've added two events to the DockManager and also to IUniDockService (that DockManager implements):

    event Action<DockItemViewModelBase> DockItemRemovedEvent;
    event Action<DockItemViewModelBase> DockItemSelectionChangedEvent;

if the item's `IsSelected` property changes - `DockItemSelectionChangedEvent` fires. 
If an item is removed - `DockItemRemovedEvent` fires.

There is a usage example under [UsingViewModelsDemo](https://github.com/npolyak/NP.Avalonia.Demos/tree/main/NP.Demos.UniDockFeatures/NP.Demos.UsingViewModelsDemo) project. The only file updated is MainWindow.axaml.cs file.

I've added:


         _uniDockService.DockItemRemovedEvent += _uniDockService_DockItemRemovedEvent;

        _uniDockService.DockItemSelectionChangedEvent += _uniDockService_DockItemSelectionChangedEvent;
        private void _uniDockService_DockItemSelectionChangedEvent(DockItemViewModelBase itemVm)
        {
            string str = $"{itemVm.DockId} {itemVm.IsSelected}";
            Console.Write(str);
        }

        private void _uniDockService_DockItemRemovedEvent(DockItemViewModelBase removedItemVm)
        {
            string str = $"{removedItemVm.DockId} {removedItemVm.IsSelected}";
            Console.Write(str);
        }

**Comment by npolyak** [comment]
The new version of the UniDock package is 1.0.42 - https://www.nuget.org/packages/NP.Avalonia.UniDock/1.0.42

**Comment by kerriganb** [comment]
oh wow! perfect (yes I use the viewmodelbase) - i'll give it a shot and let you know... exciting!!!

**Comment by npolyak** [comment]
Please do! Talk to you soon.

Nick

**Comment by npolyak** [comment]
I think I might need to add also `DockItemAddedEvent` - tell me what you think

**Comment by kerriganb** [comment]
Damn what would be awesome , didn’t even think of that.

I was hooking into collectionchanged event to figure out add, remove , but that would certainly be convenient

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by npolyak** [comment]
On Sunday too tired now :)

**Comment by npolyak** [comment]
ok, I've added DockItemAddedEvent. Please download https://www.nuget.org/packages/NP.Avalonia.UniDock/1.0.43. It also has dependency on the latest Avalonia packages.

**Comment by npolyak** [comment]
sorry, try next version - https://www.nuget.org/packages/NP.Avalonia.UniDock/1.0.44
The previous one was not good.

**Comment by kerriganb** [comment]
Hey Nick sorry for the delay ... grabbed the latest ...works like butter!

awesome. this will greatly help notify to disable processing if going in back ... closing thx!
