### ISSUE TITLE
Panel gets min width when docked after a separator has been moved

### ISSUE THREAD

**Issue by adam-adorjan** [npolyak/NP.Avalonia.UniDock#11]
Hi Nick!

Been a long time, I used to work with you at ITG.  I now work with Kerrigan on a new app that uses your awesome docking framework.  One of the issues we're seeing goes like this, could you please take a look into it?

1. Dock two panels side by side so the separator is vertical
2. Move the separator any amount, even a few pixels is enough
3. Now dock a third panel between the two existing ones

Normally the panels are proportionally sized so they would all have the same width.  Once the separator is moved however, any new panel that gets added to the stack will have the min width.  I debugged the code (super clean and easy to follow by the way), and the issue seems to be caused by the proportional/star width of the column definitions.  By default, the size is 1*.  When a splitter is moved though, the col defs will get the actual width, so could be something like [150*, 210*, 300*].  I assume Avalonia changes these from 1*, I don't see your code doing it anywhere.  The problem is that when a new panel is added to the stack, it will get the 1* width which is much smaller than the others so it will get the min width.  Same thing happens when the separators are horizontal.

I'm not sure what's the best solution here, maybe the initial width could be some kind of average of the col def widths to keep things simple.

Thanks!!

**Comment by kerriganb** [comment]
Thanks Adam for that thorough writeup! ... Hey Nick, wondering if we can ask for another similar feature ...would it be possible to add in a minwidth as well? i.e. do not allow user to minimize a splitter all the way to 0 ...maybe a percent or something ... Definitely lower priority, Adam's defect is definitely higher priority (but not urgent)

**Comment by npolyak** [comment]
Hey Guys, 
sorry for the delay answering you - I was traveling. Give me a couple of week, I'll try to fix the problems. Regards

**Comment by npolyak** [comment]
And btw, Adam, it is nice to here from you!

**Comment by npolyak** [comment]
I just uploaded the new version 1.0.45 of NP.Avalonia.UniDock - https://www.nuget.org/packages/NP.Avalonia.UniDock/1.0.45
I changed the algorithm of sizing a newly dropped pane. It now gets half the size of the pane into which it was dropped, while the pane into which it was dropped also becomes half of its previous size. 
Please check if this is what you need.
Concerning the minimum size - it was already there - the minimum size of a pane within stackdockpane is 50 pixels.

**Comment by adam-adorjan** [comment]
Thank you Nick!  We tested the change and it works well, it's more intuitive this way.

**Comment by npolyak** [comment]
Good, thanks!

**Comment by npolyak** [comment]
Please be aware I am planning to move to the new version of Avalonia within a couple of weeks. So starting about two weeks from now, all the fixes will be in Avalonia 11-preview or hopefully Avalonia 11-Rc (if Avalonia gets there)

**Comment by npolyak** [comment]
also, please, close the git issue.
