### ISSUE TITLE
How to reopen DockItem?

### ISSUE THREAD

**Issue by yaoyulian** [npolyak/NP.Avalonia.UniDock#12]
<np:TabbedDockGroup  >
<np:DockItem Header="DockItem1" Name="DockItem1" DockId="DockItem1">
<Grid Background="Red"/>
</np:DockItem>
<np:DockItem Header="DockItem2" Name="DockItem2" DockId="DockItem2">
<Grid Background="Yellow"/>
</np:DockItem>
</np:TabbedDockGroup>

in C#:   
DockItem1.Select();   Will bring DockItem1 to front.  
DockItem2.Select();   Will bring DockItem2 to front. 

If I close DockItem2, DockItem2.Select();  Will have no effect. How can I reopen DockItem2 in C#?

in addition:
If I close DockItem2 and DockAttachedProperties.GetTheDockManager(this).SaveToFile(pathString);  Then Reopen App,  DockAttachedProperties.GetTheDockManager(this).RestoreFromFile(pathString);  How can I reopen DockItem2 in C#?

**Comment by npolyak** [comment]
Hey Yaoyulian,
sorry for a delay answering you. When you close a dock item, it does not exist any more, so you won't be able to select it. You can make the item Stable, In that case you wont be able to close it. Or you can create a new item with the same content whenever you are needed and place it where you thing it belongs.
