### ISSUE TITLE
Version for Avalonia 11.0.0-preview4

### ISSUE THREAD

**Issue by kvalitetskontrollMarkaryd** [npolyak/NP.Avalonia.UniDock#14]
Will there be a version for 11.0.0-preview4?

**Comment by npolyak** [comment]
I wanted to wait until at least they have 11 RC. Someone told me that it was scheduled for last year, but apparently they did not make it. 

I am looking forward to 11 RC just the same as you do :)

**Comment by npolyak** [comment]
Ping some people at Avalonia - ask them about 11 RC and 11 full version.

**Comment by kvalitetskontrollMarkaryd** [comment]
> I wanted to wait until at least they have 11 RC. Someone told me that it was scheduled for last year, but apparently they did not make it.
> 
> I am looking forward to 11 RC just the same as you do :)

Thanks for your reply!

**Comment by kvalitetskontrollMarkaryd** [comment]
Question answered.

**Comment by npolyak** [comment]
Thanks Tobias, 
if you have not done so, ping Avalonia team about the new releases. They should know that people care about it and looking forward to it. Thanks
