### ISSUE TITLE
View width jumps to min width when docked vertically

### ISSUE THREAD

**Issue by adam-adorjan** [npolyak/NP.Avalonia.UniDock#15]
Hi Nick, thank you for the last fix!  We are seeing a related issue unfortunately.  To reproduce:

1. Dock 4-5 views horizontally next to each other.
2. Make sure they don't all have the same width
3. Drag one of the views and dock it under another one so they are stacked vertically on top of each other.
4. The group of two views stacked vertically will suddenly have minimum width.

The same thing happens in the opposite case where you stack two views horizontally in a set of vertically stacked views.

**Comment by npolyak** [comment]
Thanks for reporting it. Give me ~1 week to fix it.

**Comment by adam-adorjan** [comment]
Sounds good.  Thank you!

**Comment by npolyak** [comment]
I fixed it, please try https://www.nuget.org/packages/NP.Avalonia.UniDock/1.0.48 package version.

**Comment by npolyak** [comment]
Please, tell me how the testing went.

**Comment by adam-adorjan** [comment]
The fix works great.  Thx!
