### ISSUE TITLE
Doesn't work on Linux 

### ISSUE THREAD

**Issue by izaksuilov** [npolyak/NP.Avalonia.UniDock#17]
Hello, Nick! Your framework is extremely great, thank you for that! But I have a problem on Astra Linux (Debian-based OS) even in your example. 

![UniDock](https://user-images.githubusercontent.com/60542253/218453306-7fc83822-5d49-4eea-8966-fe1dc7c2cc88.gif)

I have the same problem in my application . Have you got any ideas how to fix it?

**Comment by npolyak** [comment]
Do you use wayland or X11? I think it might have some problems on wayland. Anyways, I'll take a look, but it might take me a bit of time. Regards.

**Comment by izaksuilov** [comment]
No, I don't use any of it. I just launched the demo project as it was. I figured out that problem is in "TransparencyLevelHint" which seems just doesn't work on that OS. Maybe instead of creating new windows, just toggle #PART_OverlayWindowHolder (grid) visibility?

**Comment by npolyak** [comment]
I'll try to take a look on Sunday

**Comment by izaksuilov** [comment]
> I'll try to take a look on Sunday

Thanks!

**Comment by npolyak** [comment]
Can you also go to your Linux xterm and type 
echo $XDG_SESSION_TYPE 
and tell me what it says?

Thanks

**Comment by izaksuilov** [comment]
> 

X11

**Comment by npolyak** [comment]
cool, thx

**Comment by npolyak** [comment]
I am using the transparent windows for displaying compass, and it seems that on Linux they are not positioned correctly. I asked the question to Avalonia platforms guru and hopefully, he'll be able to help. Will keep you informed.

**Comment by brmassa** [comment]
The same here.
Kubuntu (Ubuntu + KDE) 22.10, X11
compiled using dotnet7

**Comment by DraTeots** [comment]
Hello! Any updates?

**Comment by npolyak** [comment]
Not yet, sorry. But I am working on it whenever I can
    On Saturday, September 9, 2023 at 10:42:52 AM EDT, Dmitry Romanov ***@***.***> wrote:  
 
 


Hello! Any updates?

**Comment by npolyak** [comment]
The new version of UniDock at NP.Ava.UniDock works on Linux - dragging out not 100% but otherwise works fine.
