### ISSUE TITLE
DataContext on user control causes new instance everytime

### ISSUE THREAD

**Issue by kerriganb** [npolyak/NP.Avalonia.UniDock#5]
Hey Nick, ... using your NP.Demos.CustomViewModelsDemo as an example - in this case what I want to do is inject a user control into DataTemplate ... Works great - however whenever user moves docking tabs/items around a new instance of user control is recreated !! 

This is not good - (in my case my user control is a browsercontrol - and it literally reloads and recreates a new chrome renderer process...). 
Seems like maybe the itemscontrol or something inside unidock is causing it to recreate?

It's very easy to repo: 

 - use your NP.Demos.CustomViewModelsDemo as above
 -  create a new usercontrol 
 - add the usercontrol into your mainwindow.axaml - replace StockDataTemplate with below xaml

  
...
	xmlns:local="clr-namespace:NP.Demos.CustomViewModelsDemo"

  <DataTemplate x:Key="StockDataTemplate">
	  <local:UserControl1></local:UserControl1>
  </DataTemplate>

Now run the demo - and set a breakpoint on UserControl1 constructor ...
(create a few dockitems ...and try moving them around ...your breakpoint gets hit everytime ...recreating a new instance...)

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);   <-- this called everytime you move around
        }

as said above - this plays havoc (when my user control is a browsercontrol - cefglue) 

hopefully you have some ideas - else i'm out of luck  ... any help appreciated ...

thanks
Kerrigan.

**Comment by npolyak** [comment]
Can you create a small working sample reproducing this issue, publish it on github and share the URL with me. I'll make it work, only it will take a bit of time since both coming Sundays are going to be the Passover and I won't be able to work on them.

**Comment by npolyak** [comment]
In general, if you want a control in several dock pane - it should be reproduced. We cannot use the same instance within two different visual and logical trees

**Comment by kerriganb** [comment]
thx Nick, you are the best!!

**Comment by kerriganb** [comment]
Hey nick , sure no rush , I can hardcode as xaml as opposed to using data context for now .

Yup will create a simple demo app for you, and yes totally understand that if you have 2 dock items I would expect 2 user control instances being created , it's just that instances are created every time you move dock item.

Anyway let me get you a repo case .

Thanks
Kerrigan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kerriganb** [comment]
![shows - bug](https://user-images.githubusercontent.com/5913794/163598675-2525efd2-4d49-4aa9-b3ae-b9f8a66aeeb4.png)
[NP.Avalonia - shows bug.zip](https://github.com/npolyak/NP.Avalonia.UniDock/files/8497044/NP.Avalonia.-.shows.bug.zip)

Hi Nick - please find attached (screen shot of bug) - and a simple demo app showing the bug.

Please run the app

- if you click on button - you will see that a new browser control gets add (note: browser control just more visually shows the bug - but any user control xaml will show same problem)
- you will note that once user control is added - random number is seen ... let's say 5
- now undock and let it float (or redock) - you will see browser refreshes - and a new roll is displayed - let's say 2
- a much worse issue (then refreshing) - is that a completely NEW instance is created - but old instance is not destroyed (ideally new instance should not be created - unless you add a new item - i.e. click on button to create ...)
- if you look at screen shot - or (easier if you run outside VS studio ...) and look for process ...you will see a new browser process has been created! ...note: by just moving it - i got over 100 browser processes to be created on just 1 dock item!! :) :) 

anyway, hopefully above makes sense to you ... ideally when a new dockitem is created - you should be able to move around - redock etc...without it recreating instance ...

thanks again - love the framework - but yah - this is a major bug (or maybe i'm doing something stupid ...not sure)

Kerrigan.

**Comment by npolyak** [comment]
I'll try to help, but it will take a bit of time.

**Comment by kerriganb** [comment]
Hey nick , hope you are doing well. I’m wondering if you had a chance to look into this issue. 

Unfortunately I’m going to have to make a decision soon , if I can continue using your docking framework. This is a major issue for us. 

If you could give me a timeframe when you might be able to look at at least Would be good. 

Sorry about bumping this , 

Thanks
Kerrigan

**Comment by npolyak** [comment]
Hey Kerrigan, 
Give me another week ok?

I'll try my best to do it by next Sunday

**Comment by kerriganb** [comment]
Awesome don’t kill yourself , even a couple of weeks from now is fine . Just that biz folks are getting antsy .

Thanks again!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by npolyak** [comment]
Nice bug - thanks for catching it. I am working on it now. Not sure if this would be acceptable for you, but as a temporary workaround you can try not to use the ViewModels and insert the user control straight into a DockItem. In that case, it seems like it does not have this problem. I hope I'll fix it within several days.

**Comment by kerriganb** [comment]
Haha that’s exactly what I did , not use viewmodel and insert  directly . Sorry should have included that temp work around .

Thanks nick , much appreciated all this work you have done!!

Looking forward to the fix!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by npolyak** [comment]
OK, Kerrigan, try it again - the next version of nuget package. I think I fixed it but did not have time to thoroughly test it. Hopefully I did not screw anything else. If you find new bugs, please, report them. Even if it is not completely fixed - it should be very close.

**Comment by kerriganb** [comment]
awesome!! you are the best ... let me give it a whirl and let you know!!

**Comment by kerriganb** [comment]
Hi Nick, ... just tried out your latest version 1.0.25 of your docking library. (basically I took my repo demo - in this issue above) - and upgraded from 1.0.24 --> 1.0.25 ... **works great!!!**

- i no longer see the datacontext creating a new usercontrol everytime the window is docked/undocked !! This is great!

Unfortunately there are some other weird issues... (not sure if this was there before - since DataContext issue prevented me from testing this).

**Issue1** - Deconstructor not called - when load/save layout ... i.e. unable to clean up resources...

- This is easy to repo (again please use my repo zip file above - and upgrade to 1.0.25)
- Click on button (Nick - Click me for Bug) - and open a couple of windows
- Now click on SAVE layout - this will save layout as you expect (great)
- Now click on RESTORE layout
- I would expect the TestUserControl deconstructor to be called (the one that has the CefBrowser - btw, it's not a browser issue - you can replace with a TextBlock if you like...) - the point is - the TestUserControl never goes away (when you click restore) - hence the CefBrowser is never garbage collected - and it keeps creating new instances ...yikes...

Note: i suspect the desconstructor is never called when you click restore - for any of your demos - do we maybe have to inherit from IDisposable?? not sure how you will destroy instance or let (developer clean up after itself...) is there something i'm not doing?

![image](https://user-images.githubusercontent.com/5913794/167522529-7f4a1b80-0305-4d9e-927e-15565e8db830.png)


**Issue2** - this is a REALLY weird issue ... 

Go ahead and now upgrade Avalonia as well

![image](https://user-images.githubusercontent.com/5913794/167522502-483e4686-49b7-41d3-b5b7-701c36a9c3b2.png)

- Run the demo again ...
- click on 'Nick - Click me for Bug' button ...
- you will see you can't move drag/content - it almost looks like the user control is detached from your docking control. this is really apparent if you have multi-monitors ... put your demo on one monitor - then click on a button ... really bizarre - it's on another monitor !!!

sorry about the bugs :( ... i know you have been working hard on the fixes - this is very much appreciated ... I can go still a couple more weeks without making a decision... (don't kill yourself!!)

**Comment by kerriganb** [comment]
yah i just tried implementing IDisposable ...on TestUserControl and it's not getting called. Destructors can be called anytime from GC .. but I guess i need to know when user has closed window or layout has changed. Now I guess?? i could hook into those events - and somehow destroy my instances myself? Unless you have a better answer (would be nice if you could call - Dispose - in inherit from IDisposable ...)

thanks
Kerrigan.

**Comment by npolyak** [comment]
It is good we are weeding out the bugs now. I'll try to work on them this week, or maybe on sunday. 
Thanks!

**Comment by npolyak** [comment]
BTW, I am not sure Avalonia 0.10.14 is good and ready. I never went beyond 0.10.13 yet.

**Comment by kerriganb** [comment]
haha, that explains the REALLY bizarre things that happen when you upgrade...no worries ... there is no reason for me to upgrade...just wanted you to know :)

**Comment by kerriganb** [comment]
Hey Nick any updates on cleanup? ... do you think hooking up to close event - or layout reload event - then manually IDispose myself?

**Comment by npolyak** [comment]
I am getting there, Kerrigan.

**Comment by kerriganb** [comment]
oh no worries, just wondering ,.. i know you are busy like mad :) .... thx!

**Comment by npolyak** [comment]
Hey Kerrigan, I made the controls dispose - take a look at https://github.com/npolyak/NP.Avalonia.UniDock/tree/main/Prototypes/NP.WebBrowsersInsideUniDock. 

Unfortunately a similar demo project which has UniDock library loaded via nuget, has a problem with save/restore - a problem that seems to have nothing to do with the new code. I need to figure out what is happening there and I'll definitely do it by the end of Sunday

**Comment by npolyak** [comment]
OK Kerrigan, the latest version of UniDock should resolve all the problems you've mentioned above. Do not switch to Avalonia 0.10.14 yet. 
https://github.com/npolyak/NP.Avalonia.Demos/tree/main/WebBrowsersInsideUniDock is the working sample.

**Comment by npolyak** [comment]
Concerning the web browser software - here is a response I got to my question from one of the top Avalonia people:
He talks about AvaloniaCefBrowser that you are using. I have not tested yet, what he said.

Dan Walmsley, [5/16/2022 6:24 AM]
that solution is no longer recommended

Dan Walmsley, [5/16/2022 6:24 AM]
its recommended to use https://github.com/CefNet/CefNet now

Dan Walmsley, [5/16/2022 6:25 AM]
or

Dan Walmsley, [5/16/2022 6:25 AM]
https://github.com/OutSystems/WebView

Dan Walmsley, [5/16/2022 6:25 AM]
but the first should be better and more portable

Dan Walmsley, [5/16/2022 6:27 AM]
and the latest non-cef approach which is much more light weight as it doesnt need 100s of mb of cef libraries

Dan Walmsley, [5/16/2022 6:27 AM]
and uses the os default inbuilt browser

Dan Walmsley, [5/16/2022 6:27 AM]
https://github.com/maxkatz6/AvaloniaWebView

Dan Walmsley, [5/16/2022 6:27 AM]
but its very new!

**Comment by kerriganb** [comment]
Hi Nick, sorry for the extremely long delay in reviewing this bug. Looks like you indeed fixed the issue - I am ready to close this issue. thank you!

However, I did try upgrading to your latest 1.0.35 version (from 1.0.32) of UniDock ...and it seems that weird issue I mentioned above (with respect to Avalonia) is inherent in it. 

It's very easy to reproduce - just upgrade your WebBrowserInsideUniDock to latest version (1.0.35) and run.

not a big deal now (I will stick to your older 1.0.32 version) - though would like to upgrade if need other bug fixes - at a future point....

![image](https://user-images.githubusercontent.com/5913794/183128201-99eac266-b9a9-4784-a5ce-57f9678323c2.png)

**Comment by npolyak** [comment]
Hey Kerrigan, 
starting with some version of Avalonia (I think 0.10.14) they require an app.manifest file to mention the windows 10. Then this (separate browser window) problem disappears.

**Comment by npolyak** [comment]
take a look at https://github.com/AvaloniaUI/Avalonia/issues/8517
and https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog.NetCore/app.manifest

**Comment by npolyak** [comment]
Sorry I have not done the virtual resizing you've requested yet, but I remember about it :)

**Comment by kerriganb** [comment]
oh wow, didn't know that (re: manifest) ...will give it a shot.

And wow, yes please - would love to have the virtual resizing (no rush) - don't kill yourself ...thanks again for everything! And yes, we are finally moving forward with avalonia and unidock - yeh!!

**Comment by npolyak** [comment]
The virtual resizing is there - in the latest version of NP.Avalonia.UniDock library.

**Comment by kerriganb** [comment]
Yo da man!!! ... It works pretty darn nicely ... this is especially needed for 'heavy' controls - such as browser. Having that virtual scroll makes it pretty nice... 

However - please see attached gif - (I basically took the NP.WebBrowserInsideUniDock sample and turned on ResizePreview) ... unfortunately (the same way the dock compass was not showing ... ) the resize bar doesn't show over a browser control :(

Not sure how hard it would be to do your same 'trick' you did for compass - but I think that would be icing on the already delicious cake!

thanks again for pushing this through!
Kerrigan
![dockbar](https://user-images.githubusercontent.com/5913794/184277294-057412b5-7db2-4529-ace6-8ff30abf2aad.gif)
.

**Comment by npolyak** [comment]
Got it. I'll try to do it.

**Comment by npolyak** [comment]
Hey Kerrigan, try the newest version - should work. Sorry it took me some time - I was very busy at work and it was not the easiest thing to do.

**Comment by kerriganb** [comment]
works like a charm!!! Thank you for the hard work on it! It really helps when users move around splitters on webviews.
