### ISSUE TITLE
How to use binding?

### ISSUE THREAD

**Issue by INTERNALINTERFERENCE** [npolyak/NP.Avalonia.UniDock#7]
I don't understand how to use binding. I'm trying to do following:
```
<np:RootDockGroup TheDockManager="{StaticResource TheDockManager}">
  <np:StackDockGroup TheOrientation="Vertical">                    
    <np:StackDockGroup TheOrientation="Horizontal">                
      <np:DockItem Header="{Binding MyText}">                                    
        <TextBlock Text="{Binding MyText}"/>                              
      </np:DockItem>                                               
      <np:DockItem Header="{Binding MyText}">                                 
        <TextBlock Text="{Binding MyText}"/>                           
      </np:DockItem>
```     
But binding doesn't work after dragging tab. Also I'd like to say I can't do smth like this:
`<local:TestViewModel x:Key="TheViewModel"/>` in xaml cause of my constructor in viewmodel

**Comment by INTERNALINTERFERENCE** [comment]
hm, I defined default constructor without any props
any way my binding doesn't work

**Comment by npolyak** [comment]
For data context in UniDock, please, read [DataContext section](https://www.codeproject.com/Articles/5316702/UniDock-A-New-Multiplatform-UI-Docking-Framework-U#UsingDataContext)

**Comment by npolyak** [comment]
For binding in general - it will pick up the initial value, but in order for it to pick up the changes you need to fire INotifyPropertyChanged.PropertyChanged event in your setter and the non-visual object whose property changes needs to implement INotifyPropertyChanged interface exactly the same as in WPF. 
For visual objects - you need to use Avalonia Properties in order to be notified of the changes.

**Comment by INTERNALINTERFERENCE** [comment]
But I use reactive property that works similar to propertychanded but it doesn't work

**Comment by npolyak** [comment]
I never used Reactive attribute. I assume that either some code gets generated (how I am not sure) or something else is missing in your code.
