### ISSUE TITLE
Can not quit App after change layout

### ISSUE THREAD

**Issue by yaoyulian** [npolyak/NP.Avalonia.UniDock#8]
I use Visual Studio, Run in debug mode. if i change layout, like drag and drop DockItem, then close the app by click window's “close button”  at  top right corner, The window disappeared, but App still run in "Task Manager", and Visual Studio do not quit debug mode.  if i do not change layout, it will quit successful.
![1](https://user-images.githubusercontent.com/31014116/178114968-c563d3f4-0ad8-419e-ab73-48377acef171.png)
![2](https://user-images.githubusercontent.com/31014116/178115067-0f933d8e-d516-4583-8de1-155f7e295b1f.png)

**Comment by npolyak** [comment]
Hey Yaoyulion,

sorry for the delay answering you. I have this problem with Avalonia sometimes. I think it is not unique to UniDock. To fix it, you can create a MainWindow's Close event handler say within MainWindow.axaml.cs file and call Environment.Exit(0). This is what I sometimes do.
